name: Build - Desktop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SDL
        run: |
          git clone https://github.com/libsdl-org/SDL.git -b SDL2
          cd SDL
          mkdir build
          cd build
          ../configure
          make
          sudo make install

      - name: Build for Desktop
        run: |
          chmod -x run.sh
          bash run.sh DESKTOP